name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
      - name: Run pa11y
        run: |
          npm install -g pa11y-ci
          pa11y --ignore "issue-code-1;issue-code-2" https://mitesh411.github.io/MyResume/ 
