name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on https://mitesh411.github.io/MyResume/
      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y https://mitesh411.github.io/MyResume/
