name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18
      - name: Run pa11y
        run: |
          npm install -g pa11y-ci
          pa11y-ci --json
