name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: Run pa11y
        run: |
          npm install -g pa11y-ci
          npm install pa11y-reporter-html --save
          pa11y-ci --reporter=pa11y-reporter-html https://mitesh411.github.io/MyResume/ 
